### ISSUE TITLE
Http код ответа Selenide::open

### ISSUE THREAD

**Issue by podtserkovskiy** [razielsd/phpSelenide#9]
Можно запилить некий `Selenide::$statusCode` или даже `Selenide::$lastResponse`, который будет заполняться данными после выполнения `Selenide::open`.

**Comment by podtserkovskiy** [comment]
Хотя нет, лучше получать данные текущей страницы, так как мы можем переходить на другие страницы не только при помощи Selenide::open, но и кликая по ссылкам, и отправляя формы

**Comment by razielsd** [comment]
@podtserkovsky ты хочешь чего-то злого и не определенного, как определишься - пиши.
